In [ ]:
# task 1

In [1]:
import numpy as np

In [10]:
a = 10*np.random.rand(50)

In [11]:
a

array([5.11529738, 2.68562381, 9.77997958, 6.67305177, 0.86641233,
       4.30330408, 8.42123898, 5.46086795, 7.47149233, 4.81585256,
       9.22194523, 6.44175623, 3.90514084, 6.87383116, 6.21530202,
       2.50183923, 4.47848908, 8.603828  , 3.69777831, 3.28372091,
       2.59285383, 0.16490737, 8.3458743 , 9.97380753, 5.98524384,
       5.40517706, 5.30270377, 5.07277913, 8.15534758, 5.09129943,
       9.1867203 , 2.95389894, 5.87418235, 6.15396146, 1.53721084,
       4.54866994, 0.7879712 , 8.30913655, 0.97865716, 7.61913578,
       4.59590728, 0.47887532, 9.11066693, 0.36624711, 0.78840177,
       2.37336211, 8.41754662, 6.15336833, 9.01049438, 9.26048448])

In [5]:
a = np.floor(a)

In [6]:
a

array([3., 6., 5., 6., 8., 3., 1., 3., 0., 9., 7., 4., 0., 5., 7., 0., 3.,
       0., 2., 5., 4., 8., 7., 3., 7., 6., 6., 1., 0., 8., 0., 7., 0., 0.,
       2., 4., 0., 3., 4., 5., 8., 2., 8., 3., 7., 8., 1., 1., 4., 7.])

In [12]:
a = np.ceil(a)

In [13]:
a

array([ 6.,  3., 10.,  7.,  1.,  5.,  9.,  6.,  8.,  5., 10.,  7.,  4.,
        7.,  7.,  3.,  5.,  9.,  4.,  4.,  3.,  1.,  9., 10.,  6.,  6.,
        6.,  6.,  9.,  6., 10.,  3.,  6.,  7.,  2.,  5.,  1.,  9.,  1.,
        8.,  5.,  1., 10.,  1.,  1.,  3.,  9.,  7., 10., 10.])

In [16]:
b = a[a > 5]

In [17]:
b

array([ 6., 10.,  7.,  9.,  6.,  8., 10.,  7.,  7.,  7.,  9.,  9., 10.,
        6.,  6.,  6.,  6.,  9.,  6., 10.,  6.,  7.,  9.,  8., 10.,  9.,
        7., 10., 10.])

In [19]:
b = np.sort(b)

In [20]:
b

array([ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,
        7.,  8.,  8.,  9.,  9.,  9.,  9.,  9.,  9., 10., 10., 10., 10.,
       10., 10., 10.])

In [22]:
a = np.sort(a)[::-1]

In [23]:
a

array([10., 10., 10., 10., 10., 10., 10.,  9.,  9.,  9.,  9.,  9.,  9.,
        8.,  8.,  7.,  7.,  7.,  7.,  7.,  7.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  5.,  5.,  5.,  5.,  5.,  4.,  4.,  4.,  3.,  3.,
        3.,  3.,  3.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [42]:
arr = np.arange(18).reshape(3,2,3)
arr
type(arr)

numpy.ndarray

In [33]:
arr[:,:,1]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [32]:
arr[:1,:,1]

array([[1, 4]])

In [41]:
arr[:1,:,1]

array([[1, 4]])

In [ ]:
# 2D

In [28]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
two_d_array.shape

(2, 3)

In [30]:
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
two_d_array[0,1]

2

In [39]:
two_d_array[0:2:,0:1]

array([[1],
       [4]])

In [ ]:
# 3D

In [14]:
# Think of it as a stack of 2D arrays (depth, rows, columns)
three_d_array = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
    ],
    [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
    ],
])

three_d_array.shape


(3, 3, 3)

In [15]:
three_d_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [9]:

# 4. Slicing a subarray in one "layer":
slice_subarray = three_d_array[0, 0:2, 1:3]  # This selects a subarray from the first "layer"
slice_subarray

array([[2, 3],
       [5, 6]])

In [10]:

# 5. Slicing with step size (e.g., every other row in all "layers"):
slice_step = three_d_array[:, 0::2, :]
slice_step

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [16, 17, 18]],

       [[19, 20, 21],
        [25, 26, 27]]])

In [19]:
three_d_array[0,1,2] # depth, row, column

6

In [45]:
three_d_array[0::,1::,2::] # array depth, array row, array column
# taking first depth, 
# first row and on of all depth
# second column of first row and on of all depth

array([[[ 6],
        [ 9]],

       [[15],
        [18]],

       [[24],
        [27]]])

In [44]:
three_d_array[0:3,0:1,0:1]

array([[[ 1]],

       [[10]],

       [[19]]])

In [ ]:
# 4D 

In [2]:
shape = (2, 3, 4, 5)  # Dimensions (A, B, C, D)
four_d_array = np.random.rand(*shape)

In [3]:
four_d_array

array([[[[0.94616897, 0.55635635, 0.30420078, 0.67645012, 0.95835067],
         [0.79054347, 0.76528905, 0.09108072, 0.19241087, 0.86981898],
         [0.44415715, 0.05975985, 0.25294372, 0.90461638, 0.44931205],
         [0.28785458, 0.57605715, 0.18116933, 0.28172158, 0.84096964]],

        [[0.81164996, 0.15741708, 0.80032084, 0.95495319, 0.98644114],
         [0.38567335, 0.30722448, 0.77560501, 0.27177344, 0.62304439],
         [0.6301935 , 0.87351941, 0.48217314, 0.31189635, 0.72812925],
         [0.18762997, 0.83274442, 0.65788202, 0.43898231, 0.40336754]],

        [[0.04313833, 0.21724136, 0.9247116 , 0.21132877, 0.03604082],
         [0.08969619, 0.58444895, 0.79037622, 0.54288334, 0.39850653],
         [0.71467024, 0.19577765, 0.46208835, 0.7825262 , 0.97443899],
         [0.47268488, 0.63253886, 0.15658208, 0.96418444, 0.0134346 ]]],


       [[[0.83200163, 0.79397849, 0.41289513, 0.29858133, 0.85310931],
         [0.72389458, 0.16578507, 0.45949144, 0.97625492, 0.11478939]

In [4]:
four_d_array.shape

(2, 3, 4, 5)

In [27]:
four_d_array[0,0,0,0]

0.9461689741339491