In [1]:
import numpy as np

In [2]:
a = np.arange(100)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
b = a[3:10]
b

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
b[0] = 10

In [8]:
b
a

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
b

array([10,  4,  5,  6,  7,  8,  9])

In [10]:
b = a[3:10].copy()

In [11]:
b

array([10,  4,  5,  6,  7,  8,  9])

In [12]:
b[0]=3
b

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
a

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
b = (a == 10)

In [15]:
b

array([False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [16]:
b = (a == 10)*np.arange(a.size)

In [17]:
a.size

100

In [18]:
b


array([ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [19]:
np.argwhere?


Signature: np.argwhere(a)
Docstring:
Find the indices of array elements that are non-zero, grouped by element.

Parameters
----------
a : array_like
    Input data.

Returns
-------
index_array : (N, a.ndim) ndarray
    Indices of elements that are non-zero. Indices are grouped by element.
    This array will have shape ``(N, a.ndim)`` where ``N`` is the number of
    non-zero items.

See Also
--------
where, nonzero

Notes
-----
``np.argwhere(a)`` is almost the same as ``np.transpose(np.nonzero(a))``,
but produces a result of the correct shape for a 0D array.

The output of ``argwhere`` is not suitable for indexing arrays.
For this purpose use ``nonzero(a)`` instead.

Examples
--------
>>> x = np.arange(6).reshape(2,3)
>>> x
array([[0, 1, 2],
       [3, 4, 5]])
>>> np.argwhere(x>1)
array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])
File:      /opt/anaconda3/lib/python3.8/site-packages/numpy/core/numeric.py
Type:      function


In [20]:
np.transpose(np.zeros())

TypeError: zeros() missing required argument 'shape' (pos 1)

In [21]:
np.transpose?



Signature: np.transpose(a, axes=None)
Docstring:
Reverse or permute the axes of an array; returns the modified array.

For an array a with two axes, transpose(a) gives the matrix transpose.

Parameters
----------
a : array_like
    Input array.
axes : tuple or list of ints, optional
    If specified, it must be a tuple or list which contains a permutation of
    [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
    returned array will correspond to the axis numbered ``axes[i]`` of the
    input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
    reverses the order of the axes.

Returns
-------
p : ndarray
    `a` with its axes permuted.  A view is returned whenever
    possible.

See Also
--------
moveaxis
argsort

Notes
-----
Use `transpose(a, argsort(axes))` to invert the transposition of tensors
when using the `axes` keyword argument.

Transposing a 1-D array returns an unchanged view of the original array.

Examples
--------
>>> x = np.arange(4).

In [23]:
np.transpose(np.array([0,0,1,0]))

array([0, 0, 1, 0])

In [28]:
np.nonzero((a==10))[0][0]


3

In [26]:
np.nonzero?

Signature: np.nonzero(a)
Docstring:
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order.

To group the indices by element, rather than dimension, use `argwhere`,
which returns a row for each non-zero element.

.. note::

   When called on a zero-d array or scalar, ``nonzero(a)`` is treated
   as ``nonzero(atleast_1d(a))``.

   .. deprecated:: 1.17.0

      Use `atleast_1d` explicitly if this behavior is deliberate.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the inp

In [30]:
np.argwhere(a == 10)[0][0]

3

In [50]:
r = np.round(10*np.random.rand(3,3))

In [51]:
r

array([[8., 1., 8.],
       [2., 3., 5.],
       [8., 9., 9.]])

In [53]:
r[:,2]

array([8., 5., 9.])

In [36]:
r[1,0:1]

array([2.])

In [37]:
r[:,1]

array([6., 2.])

In [38]:
r[:]

array([[3., 6., 4.],
       [2., 2., 4.]])

In [54]:
r[0,:]

array([8., 1., 8.])

In [56]:
l = np.round(10*np.random.rand(3,3,4))

In [57]:
l

array([[[ 3.,  7.,  8.,  5.],
        [ 8.,  5.,  8.,  3.],
        [ 0.,  4.,  2.,  3.]],

       [[ 4.,  1.,  6.,  2.],
        [ 8.,  2.,  4.,  1.],
        [ 4.,  2.,  3.,  1.]],

       [[ 1.,  1.,  3.,  7.],
        [ 7.,  8.,  9.,  8.],
        [10.,  8., 10.,  7.]]])

In [59]:
l[1,0]

array([4., 1., 6., 2.])

In [60]:
l[1,0,0]

4.0

In [61]:
l[:,0]

array([[3., 7., 8., 5.],
       [4., 1., 6., 2.],
       [1., 1., 3., 7.]])